// Generated by https://quicktype.io
import 'dart:convert';

class BooksModel {
  String? id;
  VolumeInfo? volumeInfo;

  BooksModel({
    this.id,
    this.volumeInfo,
  });

  factory BooksModel.fromMap(Map<String, dynamic> map) {
    return BooksModel(
        id: map['id'], volumeInfo: VolumeInfo.fromMap(map['volumeInfo']));
  }
}

class VolumeInfo {
  String? title;
  List<String>? authors;
  String? publisher;
  String? publishedDate;
  String? description;
  int? pageCount;
  List<String>? categories;
  double? averageRating;
  ImageLinks? imageLinks;
  String? language;
  String? previewLink;

  VolumeInfo({
    this.title,
    this.authors,
    this.publisher,
    this.publishedDate,
    this.description,
    this.pageCount,
    this.categories,
    this.averageRating,
    this.imageLinks,
    this.language,
    this.previewLink,
  });

  factory VolumeInfo.fromMap(Map<String, dynamic> map) {
    return VolumeInfo(
        title: map['title'],
        authors: (map['authors'] as List<dynamic>?)?.cast<String>(),
        publisher: map['publisher'],
        publishedDate: map['publishedDate'],
        description: map['description'],
        pageCount: map['pageCount'],
        categories: (map['categories'] as List<dynamic>?)?.cast<String>(),
        averageRating: (map['averageRating'] is int)
            ? (map['averageRating'] as int).toDouble()
            : map['averageRating'],
        /*voteAverage: (map['vote_average'] is int)
            ? (map['vote_average'] as int).toDouble()
            : map['vote_average'],*/
        imageLinks: ImageLinks.fromMap(map['imageLinks']),
        language: map['language'],
        previewLink: map['previewLink']);
  }
}

class ImageLinks {
  String? smallThumbnail;
  String? thumbnail;

  ImageLinks({
    this.smallThumbnail,
    this.thumbnail,
  });

  factory ImageLinks.fromMap(Map<String, dynamic> map) {
    return ImageLinks(
        smallThumbnail: map['smallThumbnail'], thumbnail: map['thumbnail']);
  }
}
